[project]
name = "desafio-matera-credito"
version = "1"
requires-python = ">=3.9"
dependencies = [
    "django==4.2.20",
    "djangorestframework==3.15.2",
    "drf-yasg==1.21.8",
    "numpy==1.24.3",
    "pip-tools"
]