# Generated by Django 4.2.20 on 2025-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_already_paid',
            field=models.BooleanField(default=False),
        ),
    ]
