# Generated by Django 4.2.20 on 2025-04-18 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_amount_alter_loan_monthly_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan'),
        ),
    ]
